aiidalab/aiidalab-qe

- codes.py
This needs to be done before releasing aiidalab-1.0
> Fix pseudo families

- .github/workflows/ci.yml
> Add 'continuous-integration' workflow.

- .github/workflows/ci.yml
> Run app tests with aiidalab/aiidalab-test-app-action@v2.

- .github/workflows/ci.yml
- tests/test_qe_app.py
Add selenium unit tests for this app.
> Add unit tests

- .github/workflows/ci.yml
- qe.ipynb
And custom docker image that does not fail with pre-mounted apps.
> Test with action supporting app names.

- .github/workflows/ci.yml
- .gitignore
- metadata/compile.py
- metadata/requirements.txt
- metadata/templates/index.html
- metadata/templates/metadata.json.in
The metadata.json file contains metadata information about this app that
transcends versions so should ideally be published independently of a
specific repository commit.
This commit adds both a script for the compilation of the metadata.json
file from a template and a GitHub actions workflow for its publication.
> Add script for the automated compilation of the metadata.json file.

- bands.py
The inheritance model with CodeSubmitWidget as parent proved to be too
inflexible.
> Move logic from CodeSubmitWidget to ComputeBandsSubmitWidget.

- pseudos.py
- workflow.py
This also involves a significat rearrangement of the setup class.
> Change the appearance of calc configuration step.

- qe.ipynb
Requires https://github.com/aiidalab/aiidalab-widgets-base/pull/209
https://user-images.githubusercontent.com/1441208/123243613-79240300-d4e3-11eb-92d4-3d091f87d027.mp4
Closes #74.
> Use automated bug report on app crash.

- aiidalab_qe/steps.py
Fixes #90 
Fixes #76 
Rearrange the content of the "Workflow" tab in step 2 of the QEapp:
Make a separate header for "Structure" where the selection of the
geometry optimization is done via three options:
* Structure as is (`RelaxType.NONE`)
* Atomic positions (`RelaxType.POSITIONS`)
* Full geometry (`RelaxType.POSITIONS_CELL`)
The "material settings" are also moved into the `WorkChainSettings`, and
placed right below the geometry optimization choice with some more
explanation.
The next header is still "Properties", but (for) now only the band
structure can be chosen here.
Finally, the "Protocol" header and content has remained the same as
before, but is not the final thing users can choose in this tab.
> 👌 IMPROVE: Step 2 Workflow tab

- aiidalab_qe/steps.py
> Fix erroneous `display` in alert message

- aiidalab_qe/steps.py
> Add sentence on definition of k-points distance value

- aiidalab_qe/steps.py
> Automatically select code after installation.

- setup.cfg
I discovered two issues with the current bumpver config, which should be fixed with this change.
> CI: Fix the bumpver config

- aiidalab_qe/process.py
> Detail of wf info in workchain selector

- qe.ipynb
> Add footer with copyright and version information.

- aiidalab_qe/setup_codes.py
> Allow manual trigger of code setup after failure.

- aiidalab_qe/steps.py
Currently the `PdosWorkChain` runs the `projwfc.x` and `dos.x`
calculations with the full number of MPI ranks specified by the user,
without any kind of parallelization. This can cause failures when the
number of MPI ranks exceeds the number of FFT slabs in the
decomposition.
Here we use the same parallelization settings for the `projwfc.x`
calculation. For the `dos.x`, there is no parallellization implemented,
but this post-processing step is typically very fast, so we simply limit
the number of MPI ranks to the value that we used to set the default
number of `npools`.
> Limit MPI ranks for `projwfc.x` and `dos.x`

- aiidalab_qe/report.py
- aiidalab_qe/static/workflow_summary.jinja
- aiidalab_qe/steps.py
- qe.ipynb
- src/aiidalab_qe_workchain/__init__.py
- src/setup.py
Fixes #64 
The WorkChain has also changed so the workchain need to be released and change the dependency info. 
@mbercx What is the correct workflow to make the PR when the work chain is changed? Should those change in another PR and release first?
> Add smearing width and type set

- tests/test_qe_app.py
This reverts commit f2d840de219a8d2ab70b9811652ff0c936338323.
Hi @csadorf, sorry for the back and forth, hope I do it right about this revert.
> Revert "fix: downstream ci"

- setup.cfg
> qeapp.yml install as package_data

- aiidalab_qe/report.py
This is a quick fix for #259, but when I look at the code, I find there could be some problem with the parameters not properly set from `qeapp.yaml`. 
So if it is not extremely emergence, I'll dig into it more and update this PR. What you thought? @csadorf
> Fix: Pure relaxation fails

- qe.ipynb
As mentioned by @danielhollas, the tabs order can be set. This PR is independent of https://github.com/aiidalab/aiidalab-widgets-base/pull/328.
> Move cell tab to front in structure viewer

- LICENSE
- README.md
- setup.cfg
This is required by Big-MAP and they said the phrase should be exactly the same as I added in front of the original Ack section. 
The LICENSE is added as well.
> Acknowledgements required by BigMAP

- aiidalab_qe/node_view.py
fixes #268 
If both bands and dos calculations are run, using the fermi energy from nscf results of dos calculation. Otherwise using the fermi energy from bands calculation is not scientifically robust.
> band structure use dos fermi energy if exist

- aiidalab_qe/steps.py
I just made a test and find I forget the update when using the new `aiidalab-widget-base`.
> The api change after bump the widget base

- aiidalab_qe/parameters/qeapp.yaml
- aiidalab_qe/pseudos.py
- aiidalab_qe/report.py
- aiidalab_qe/sssp.py
fixes https://github.com/aiidalab/aiidalab-qe/issues/346
> Bump version using SSSP v1.2

- aiidalab_qe/node_view.py
This PR enhances the view of electronic structure.
User can 
- select dos_type (`atom` or `orbital`).
- change the energy range.
- plot or hide the fermi level line.
Here is a screenshot:
> Enhance view for the electronic structure

- aiidalab_qe/node_view.py
- aiidalab_qe/steps.py
- aiidalab_qe/version.py
- setup.cfg
- src/aiidalab_qe_workchain/__init__.py
- src/setup.cfg
This PR adds a few simple input settings to enable XAS calculations with the `XspectraCrystalWorkChain` through the App, building on existing inputs provided by the XPS implementation. At present, this includes a means to provide [core wavefunction data files](https://github.com/aiidalab/aiidalab-qe/commit/78cb09381ee0a018a6341be8ccfdb52c592c75f2) as well as a simple plotting widget to display all finalised XAS produced by the WorkChain.
> XAS: Basic Implementation of XAS Calculations

- aiidalab_qe/__init__.py
- aiidalab_qe/app/__init__.py
- qe.ipynb
> Move module imports from __init__.py of package to app modules

- aiidalab_qe/app/steps.py
> Fix transfer to final step issue

- aiidalab_qe/app/parameters/qeapp.yaml
- aiidalab_qe/app/setup_codes.py
- aiidalab_qe/app/steps.py
> bump to use qe 7.2 from conda-forge

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/report.py
- src/aiidalab_qe/app/submission/__init__.py
- tests/conftest.py
- tests/test_submit_qe_workchain.py
- move get_configuration_parameters from submission to configuration
- link the value of the `configuration  step` to the `input_parameters` of the submit step
> move get_configuration_parameters from submission to configuration

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/configuration/workflow.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/workflows/__init__.py
- tests/conftest.py
- tests/test_configure.py
- tests/test_submit_qe_workchain.py
- use panel for the `workchain_setting` and the `advanced_setting`
- pass `parameters` to the builder, and let the plugin developer decide how to use the parameters.
- add test for configuration step. I skipped the test for set_configuration_parameters because it needs changes in code in the magnetization
> use panel for workchain and advanced setting

- .github/workflows/ci.yml
- src/aiidalab_qe/app/configuration/advanced.py
- tests/configuration/test_advanced.py
This PR adds a HTML displaying the mesh that is going to be use in the calculations based on the kpoints_distances used. This was one issue in #418
> Adding HTML widget to show the kpoint setting changes

- src/aiidalab_qe/app/submission/__init__.py
- tests/test_codes.py
fix #520. Remove the code blocker when updating code widgets.
> remove blocker when updating code

- setup.cfg
This PR update aiidalab-widgets-base to allow the app to visualize the supercell implementation from @superstar54
> Bump aiidalab-widgets-base to version 2.1.0b0

- docs/source/installation/access_aiidalab/vm.rst
Link and instructions for:
- M1/M2 apple silicon
- x86_64
> Add links and instructions on running with Quantum Mobile images

- setup.cfg
> Include xas yaml in package data

- README.md
Please also check the linked wiki and update the text directly if anything not proper.
> Update README.md for release management

- docs/source/conf.py
- setup.cfg
- src/aiidalab_qe/version.py
Repalce https://github.com/aiidalab/aiidalab-qe/pull/647
> Bump version v24.04.0a2 -> v24.04.0a3

- Dockerfile
> Slim image without fix-permissions on CONDA_DIR

- src/aiidalab_qe/common/bandpdoswidget.py
This PR address #821 #812 
The PR involve these changes
Here a test with Tot_magnetization, 
Test Au, using labels in StructureData ,
> Updating bandspdos widget

- src/aiidalab_qe/app/result/__init__.py
This fixes https://github.com/aiidalab/aiidalab-qe/issues/845
Hi @AndresOrtegaGuerrero , @superstar54 , could you please try again, to see if the PR solves your issue? thanks a lot
> Backward compatibility issue

- plugin_list.ipynb
- plugins.yaml
This fixes https://github.com/aiidalab/aiidalab-qe/issues/869
> Improving plugins list page and plugins description

- src/aiidalab_qe/common/widgets.py
There was an extra Note in the caption , that i missed , this PR just removes this
> removing extran note caption

- docs/source/conf.py
> Add icon links in docs to website and repo

- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
> Set fat_bands=True when FatBands is required

- src/aiidalab_qe/common/widgets.py
> Change select periodicity description to apply

- src/aiidalab_qe/app/result/components/summary/model.py
- src/aiidalab_qe/app/static/templates/workflow_list_summary.jinja
- src/aiidalab_qe/app/static/templates/workflow_table_summary.jinja
- tests/test_result.py
> Add initial structure pk to summary

- src/aiidalab_qe/common/bands_pdos/utils.py
> Use backwards compatible methods to extract output parameters

- setup.cfg
> Unpin pymatgen

- Dockerfile
- src/aiidalab_qe/app/parameters/qeapp.yaml
- src/aiidalab_qe/common/setup_codes.py
- src/aiidalab_qe/setup/codes.py
This Pr upgrades QE to 7.4
- QE inside the docker image
- QE inside AiiDA code setup
> Upgrade QE to 7.4 in docker image

- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/basic/model.py
Leftovers from #984
Resolves #1131
> Move resetting of `spin_orbit` to the basic settings model

- src/aiidalab_qe/app/submission/global_settings/model.py
- src/aiidalab_qe/app/submission/model.py
- src/aiidalab_qe/common/mixins.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/workflows/__init__.py
- tests/conftest.py
- tests/test_codes.py
- tests/test_submit_qe_workchain.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
This PR allows us to use nested traits as dependencies, e.g.,
```python
dependencies = [
'input_structure',
'advanced.pseudos.functional'   # <===   here is the example
]
```
> Support nested dependency

- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/utils/search_jobs.py
- src/aiidalab_qe/common/mixins.py
- src/aiidalab_qe/common/process/__init__.py
- src/aiidalab_qe/common/process/state.py
- src/aiidalab_qe/common/process/tree.py
This PR defines process state icons in a separate common module and utilizes them throughout the app.
> Codify state icons in a separate module

- src/aiidalab_qe/app/configuration/advanced/model.py
This PR , set the total_magnetization value in the advanced tab when loading a previous calculation
> Total Magnetization in Advanced

- src/aiidalab_qe/app/result/components/viewer/viewer.py
> Add missing in-app-guides hook in results panel

- setup.cfg
Fix #1212 .
Add the guides to the package data.
> Add guides to the package data

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/common/widgets.py
This PR does the following:
- Separate and reorder thresholds UI
- Add documentation w.r.t number of atoms scaling
- Add labels showing the actual values (Ry) used in the calculation
Resolves #1220
> Clarify use of thresholds

- src/aiidalab_qe/app/structure/__init__.py
Suggested by @giovannipizzi , this PR changes LiCoO2 to LiCoO₂
> Use subscript for the structure label in the dropdown

- src/aiidalab_qe/common/process/tree.py
Applying workaround to migrated `Data` node issue - see #1214
> Fix `Data` node issues in tree

- .github/workflows/docker-build-test-upload.yml
- Dockerfile
Fix #1255 
Push the image to Docker Hub.
> Push image to docker hub

- before-notebook.d/43_start-hq.sh
- src/aiidalab_qe/app/submission/global_settings/model.py
- tests/test_codes.py
This is a quick solution to tell the user that the code is not showing because probably the calculation (already finished) has been imported. I just add another point to the blocker:
> Adding a warning in the code blocker

- setup.cfg
- src/aiidalab_qe/common/widgets.py
This fixes https://github.com/aiidalab/aiidalab-qe/issues/1209
> Adding check for needed plugins

- setup.cfg
Use `aiidalab-widgets-base` from the repo
> Use AWB from the repo

- .github/workflows/docker-build-upload.yml
- Dockerfile
Split Docker builds by arch and add multi-arch manifest creation
- Build amd64 and arm64 separately to reduce runner disk usage
- Build arm64 on the github arm runner
- Use `imagetools create` to merge into multi-arch image
> build amd and arm separately and then merge into one

- src/aiidalab_qe/guides/0_Basic tutorial (relaxation, bands, PDOS).html
- Removed redundancies
- Added note regarding potential "failed" relaxation workflows
> Update basic tutorial

- src/aiidalab_qe/app/configuration/advanced/smearing/smearing.py
> Add lower bound of 0 (QE default) to smearing width

- src/aiidalab_qe/app/configuration/advanced/pseudos/pseudos.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/uploader/model.py
- tests/conftest.py
- tests/test_pseudo.py
- tests/test_result/test_summary_report.yml
This PR simplifies the pseudopotential session test fixtures. It also updates the tests, which now reflect correct pseudopotentials w.r.t the codebase.
> Fix pseudopotential fixtures and tests

- src/aiidalab_qe/app/wrapper.py
> Missed one last `LoadingWidget` import
