aiidalab/aiidalab-qe

- qe.ipynb
Currently it is no possible to link `selected_code` traits of
CodeDropdown widget. Commenting it out till the issue is fixed.
Link: https://github.com/aiidalab/aiidalab-widgets-base/issues/60
> Temporary fix for the code selection.

- qe.ipynb
- requirements.txt
According to https://github.com/aiidalab/aiidalab-optimade/blob/83fdcb60cfb1d87faba48038f7ba3cba771f2c83/aiidalab_optimade/widget.py#L12
> 🐛 FIX: OptimadeQueryWidget moved to aiidalab_widgets_base

- qe.ipynb
The pybel module must be imported as
from openbabel import pybel
instead of
import pybel
This monkeypatch enables the second import as well.
> Monkeypatch the pybel import path.

- node_view.py
- report.py
A couple of changes are made to the report of the input parameters:
* Add the plane wave energy cutoffs to the report. In order to do this, separate the `yield`ed energy cutoffs so they aren't reported as a dict. (Since I didn't know if that would work in the jinja template 😅 ) 
* Show the k-points line distance of the `'bands'` calculation in case the band structure is computed.
* Show the k-points mesh distance of the `'nscf'` calculation in case the PDOS is computed.
* In case the pseudo family isn't provided (i.e. equal to `None`), use the `protocol` to determine the `pseudo_family`.
> Update results report of inputs params

- aiidalab_qe/parameters/__init__.py
- aiidalab_qe/parameters/qeapp.yaml
- aiidalab_qe/pseudos.py
- aiidalab_qe/steps.py
- setup.cfg
Fixes #67 
Several changes are made to clean up/refactor/modularize the widgets:
* Move defaults into `.yaml` that is read and used consistently. Use
`importlib_resources` for importing this into modules.
* Try to add consistency between the order of these default in the .yaml
file and how they are ordered in several commands of ths
`SubmitQeAppWorkChainStep`.
* Rename `configs` to `settings` (save for `code`, this was included in
PR #71).
* Fix issue where _both_ `OptionsConfig` (now `AdvancedSettings`) and
`SubmitQeAppWorkChainStep` would intialize a `PseudoFamilySelector`,
leading to issues in correctly assigning the pseudos.
Note that there is a small change in UI: The Materials Settings have
been moved outside of expert mode, since the layman usually can still
understand/decide …
> ♻️ REFACTOR: defaults and widgets of the steps

- .pre-commit-config.yaml
- aiidalab_qe/node_view.py
- aiidalab_qe/parameters/__init__.py
- aiidalab_qe/report.py
- aiidalab_qe/static/style.css
- aiidalab_qe/static/welcome.jinja
- aiidalab_qe/static/workflow_summary.jinja
- qe.ipynb
Fixes #57 
Change the workflow summary to have two tables with the "WorkChain
setings" and the "Advanced Settings". Fix several pieces in the code to
make sure the output it obtained correctly.
Other changes: 
* Move to using jinja files and CSS to write down these somewhat
larger HTML parts that can do with some styling.
* Add `isort` to the `pre-commit` config and have it play nice with `black`.
* Switch to using builtin `importlib.resources` instead of the backport
`importlib_resources`.
> 👌 IMPROVE: Workflow summary

- aiidalab_qe/node_view.py
> Fix the structure appearance in the final geometry tab.

- aiidalab_qe/report.py
- aiidalab_qe/steps.py
- aiidalab_qe/widgets.py
- The user can only specify the total number of MPI tasks.
- The number of nodes is automatically determined from the selected
code.
- The number of total number of MPI tasks is automatically adjusted
based on the selected structure.
- Warnings are displayed to the user if the resource selection is not
appropriate for the local host.
> Revise the user resource selection.

- aiidalab_qe/node_view.py
- aiidalab_qe/steps.py
- qe.ipynb
- setup.cfg
> Running PDOS workchain and plot bands + pdos

- qe.ipynb
Instead of displaying the cryptic .qe-0.ipynb, etc.
Fixes #185.
> Update browser window title to human-readable name.

- aiidalab_qe/setup_codes.py
- aiidalab_qe/steps.py
- aiidalab_qe/widgets.py
Fixes #83 
Fixes #163
Fixes #79
Slight overhaul of the resource specification for the work chain:
* Disable the PDOS codes if the property is not calculated.
* Add a check to make sure that all codes are run on the same computer
if the PDOS is calculated.
* Allow the user to specify both #nodes and #CPUs for remote codes.
For the localhost codes the "nodes" widget is disabled. Defaults and
maxima of the number of CPUs is set based on the number of CPUs and the
default number of MPI processes.
* Allow to specify the parallelization. A default value is set to try
and avoid parallelization issues with too many MPI processes.
* Add `export OMP_NUM_THREADS=1` to `localhost` code setup.
Beside these changes, the builder is now properly updated to use the
specified resources and parallelization …
> IMPROVE: Rework resource specification

- src/aiidalab_qe_workchain/__init__.py
Fixes #195 
When both the band structure and PDOS are calculated, the
`QeAppWorkChain` will restart the `nscf` for the `PdosWorkchain` from
the `scf` calculation in the `PwBandsWorkChain`. However, the
`PwBandsWorkChain` will also primitivize the structure via Seek-path.
This meant that the input structure for the `nscf` calculation did not
match the one that Quantum ESPRESSO finds in the `data-file-schema.xml`
for the restart, causing the calculation to crash.
Here we set the `current_structure` in the work chain context to the
primitive one obtained from SeeK-path in the `inspect_bands` step of the
outline.
> 🐛 FIX: use primitive structure for PDOS `nscf` restart

- aiidalab_qe/node_view.py
- aiidalab_qe/report.py
Fixes #204 
Fix two issues when calculating only the PDOS:
* Show the correct energy cutoffs and k-points distance for the SCF.
* Properly show the "Electronic Structure" output, which currently isn't
shown because the `_update_view` method only checks for the
`band_structure` output.
> FIX: Reporting when only PDOS is calculated

- README.md
For aiidalab app development, the changes in a notebook will show after the page refresh and all imported libraries will reload if there are any latest changes. pip install the package with edit mode has the issue that it is going to write files into `/opt/conda/lib` which raise permission disallowed exception.
> DOC: no need to use edit mode even for developer

- setup.cfg
Thanks for @dou-du 's work, we can now distinguish up and down spins in red and black lines when showing the band structure.
> Deps: update widget-bandsplot to 0.2.8

- .github/workflows/ci.yml
- .pre-commit-config.yaml
As described in https://github.com/aiidalab/aiidalab-qe/pull/206#issuecomment-1081661847, the ci test failed since an installation issue. ~~Temporarily disabled it and enable it after it is fixed on pre-commit side.~~ Pining virtualenv version to workaround, which needs to be removed after issue fixed.
> CI: temporarily disable pre commit

- aiidalab_qe/node_view.py
- src/aiidalab_qe_workchain/__init__.py
Fixes #202 
Currently it is not possible to calculate the PDOS for a spin-polarised
system (i.e. setting Magnetism to Ferromagnetic), since the
`QeAppWorkChain` expects the `projections` output from the
`PdosWorkChain`. However, for spin-polarised systems the
`ProjwfcCalculation` returns two outputs: `projections_up` and
`projections_down`.
Here we adapt the `QeAppWorkChain` to check for the `projections_up`
output, and in case it is present it will add both `projections_up` and
`projections_down` to the outputs. Otherwise it will only add the
`projections` output (both only in case the `workchain_pdos` was
actually run).
To deal with plotting the corresponding (P)DOS, we simply add the total
DOS up and down states together, and separately add the PDOS orbitals
for the up and down states …
> FIX: Running PDOS for spin-polarised system

- setup.cfg
Metadata read by aiidalab-registry expect a list for `categories` in `setup.cfg`. This is subtle mistake and hard to find when writing metadata.
We'd better then add an example in the documentation for this field. Or you think it is possible to add a schema check somewhere for it? @csadorf 
EDIT: Add my name to the author list.
> aiidalab-registry expect list for categories in setup.cfg

- aiidalab_qe/steps.py
There is no such attribute `input_structure` of class `ConfigureQeAppWorkChainStep`. Although this cause nothing when reset in the configure step (I am surprised this does not raise any exception🧐), anyway should be deleted.
> Fix: Leftover reset of input_structure in ConfigureStep

- aiidalab_qe/setup_codes.py
- aiidalab_qe/sssp.py
> Set installed traitlets of pseudo/qe install widget when it's done

- aiidalab_qe/report.py
- aiidalab_qe/steps.py
fixes #275 
The `run_bands` and `run_dos` are poped out from builder_parameters which is not needed and will then not be set as extra attributes of workchain.
It cause the issue that the report of the calculation is not correctly prepared.
> Not pop run_bands/pdos from builder parameters

- aiidalab_qe/steps.py
Follow up on https://github.com/aiidalab/aiidalab-widgets-base/pull/336, see discussion there.
(I tested this in my own app, but suppose it works here too)
> Fail if process exits with non-zero status

- aiidalab_qe/widgets.py
When the CalcJob is finished, we can fetch the output file from the `retrieved` folder instead of always going through the `remote_folder`. Besides performance reasons, this works better when the remote folder is cleared.
Note that I have tested this only in the context of my own AiiDAlab app where I am reusing this code, but I see no reason why it shouldn't work here as well (please test).
> CalcJobOutputFollower: Fetch retrieved output file if available

- aiidalab_qe/node_view.py
- aiidalab_qe/process.py
- aiidalab_qe/pseudos.py
- aiidalab_qe/report.py
- aiidalab_qe/static/welcome.jinja
- aiidalab_qe/static/workflow_summary.jinja
- aiidalab_qe/steps.py
- qe.ipynb
fixes #277 
Update text on feedback from Nicola.
> Text review and update

- aiidalab_qe/parameters/qeapp.yaml
- aiidalab_qe/setup_codes.py
- aiidalab_qe/steps.py
> bump conda installed qe version to latest 7.0

- aiidalab_qe/steps.py
> Change spin/electronic type setting to toggle

- setup.cfg
New aiidalab-widgets-base include lots new features shown in https://github.com/aiidalab/aiidalab-widgets-base/releases/tag/v1.4.0
> bump aiidalab-widgets-base version to 1.4.0

- aiidalab_qe/process.py
- aiidalab_qe/report.py
- aiidalab_qe/steps.py
- src/aiidalab_qe_workchain/__init__.py
fixes #264 
Using `RelaxType.NONE` for relax workchain to run the SCF only. 
The builder is constructed with all three workchain input parameters port, `relax`, `bands`, `pdos`.
Whether to run  sub-workchain is controlled by popping the input key out from the builder, right after the builder is created. 
Also, the relax/properties infos of workchain selector is changed to show this newly add calculation type as 'SCF only'.
> Set relax type none and no properites to run SCF only

- setup.cfg
The issue https://github.com/aiidalab/aiidalab/issues/326 is caused from the `#` symbol is requirements list of `setup.cfg`.
> Remove # symbol in requirements which break the deps check

- aiidalab_qe/report.py
- aiidalab_qe/steps.py
fixes #318 
@superstar54 We had a discussion about this, seems I didn't change these parts of code back to normal.
> run_relax should be used for get pw-parameters

- .pre-commit-config.yaml
- tests/conftest.py
- tests/test_qe_app.py
fixes #343 
Using the fixture `final_screenshot` to take the screenshot for smoke tests at the end of tests. 
In this PR, I also try to use the `WebDriverWait` to load the element without explicitly waiting.
> Final screenshot fixture

- aiidalab_qe/node_view.py
- aiidalab_qe/steps.py
- aiidalab_qe/widgets.py
- qe.ipynb
~~Combined with https://github.com/aiidalab/aiidalab-widgets-base/pull/430 should fix #344~~
fixes #344 
The `register_viewer_widget` decorator registers the viewer by class and the new viewer for QeAppWorkchain specifically also become the viewer of other WorkChain. It will raise the `KeyError` and raised which is not expected. 
Instead of raising the exception, nothing is returned. This is a workaround since ideally if there is no new specific viewer defined for a specific work chain, it needs to fall back to the native one of AWB. As tried in https://github.com/aiidalab/aiidalab-widgets-base/pull/430
> Fix issue workchain viewer not designated for workchains except QeAppWorkchain

- setup.cfg
- src/setup.cfg
- `aiida-core~=2.2` to align with aiida-core version in new docker stack
- `aiidalab-widget-base==2.0.0b5` for pinning the `widgetnbextension` version https://github.com/aiidalab/aiidalab-widgets-base/pull/467
- `widget-bandsplot~=0.5.1` for fixing TDOS background filling issue.
> bump version of aiidalab-widgets-base and widget-bandsplot

- setup.cfg
Jinja2 and importlib are from aiida-quantumespresso, therefore the version is loosely pinned. The pybtex has to be added to work around the installation issue.
> bump AWB to released 2.0

- setup.cfg
`aiidalab-widgets-base` 2.0 is released, the version is bump here. Jinja2 and importlib are from aiida-quantumespresso, therefore the version is loosely pinned. The pybtex has to be added to work around the installation issue.
> bump AWB to released 2.0 (#394)

- setup.cfg
This fix https://github.com/mbarkhau/bumpver/pull/207 is what I did and needed to release old support (e.g. v23.04.3) after there are new released (v23.10.0a0).
> Using new bumpver to support backport version release

- setup.cfg
The dependency is pinned by `aiida-quantumespresso==4.4.0`, which not release yet. Revert after the aiida-quantumespresso bump.
> Restrict pydantic to fix testing

- aiidalab_qe/app/sssp.py
QeApp failed when installing SSSP pseudo, because the new SSSP version (1.3) is released, and we hard-coded version 1.2 in QeApp, so we need to add the version when installing pseudo.
> add version when installing pseudo

- setup.cfg
In order to use https://github.com/mbarkhau/bumpver/pull/207 for backport compatibility support for branch `support-23.04.x`.
> Bump bumpver to 2023.1124

- setup.cfg
The installation broke by `pymatgen`, again. 😞 
For the "stable" `23.04.x` support, I think the only way is to keep on bump the patch version with the fix which means endlessly pining/unpinning the pymatgen with specific versions.
For `23.10.0`, I'll try to introduce the `pip-compile` and `pip-sync` to solve this once for all if we really can not get rid of `pymatgen` (we should try at least @mbercx).
> pinning more specific aiida-core and aiida-qe

- setup.cfg
`pybtex` is a dependency of `pymatgen` and was pinned to a workaround of a installation issue before. The `pymatgen` was pinned to accelerating the installation other wise the pip will take a long time to solve the dependencies. 
But the version `pymatgen==2022.9.21` now cause the error:
```
gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /opt/conda/include -fPIC -O3 -isystem /opt/conda/include -fPIC -I/tmp/pip-build-env-1bww2zm1/overlay/lib/python3.9/site-packages/numpy/core/include -I/opt/conda/include/python3.9 -c pymatgen/optimization/linear_assignment.c -o build/temp.linux-aarch64-cpython-39/pymatgen/optimization/linear_assignment.o
In file included from …
```
> Remove pinning pymatgen

- src/aiidalab_qe/app/submission/__init__.py
Setting new pseudopotential is not properly work, I did some refactoring during rebase and this change is needed.
I tried to write the test for this but failed to do it, I notice @AndresOrtegaGuerrero put similar tot_charge test in `submit_step_widget_generator` fixture. I think the better way would be to verify the data pass to create `QeWorkChainParameters` dataclass.
Since I'll take over @superstar54's PR to prototype some unit tests, I'll leave this task there.
> Pseudo setter override pseudos properly

- src/aiidalab_qe/app/configuration/advanced.py
This PR increases the value of the magnetization widget, the values -1, 1 were too limited leading to low starting_magnetization values in the pw.x calculation
> increasing the range of the magnetization floattext

- setup.cfg
- src/aiidalab_qe/app/common/panel.py
- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/workflow.py
- src/aiidalab_qe/app/plugins/bands/__init__.py
- src/aiidalab_qe/app/plugins/bands/result.py
- src/aiidalab_qe/app/plugins/bands/setting.py
- src/aiidalab_qe/app/result/workchain_viewer.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/app/utils/__init__.py
- src/aiidalab_qe/workflows/__init__.py
- tests/test_entry_point.py
- tests/test_panel.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
This PR uses the plugin design to implement a basic version of `bands`. It only adds the `UI` part:
- setting panel, It is only used to illustrate that the setting panel appears when the user selects the bands property. No parameters from this panel are used in the workchain.
- result panel. This is a panel only to show the bands. The code for `electronic_structure` tab is still kept.
> Plugin band

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/submission/__init__.py
- tests/configuration/test_advanced.py
- tests/conftest.py
- Remove override of sub-widgets of advanced setting
- Proper white box tests are added for widgets
- Move kpoints setting and totalchange setting into the advanced setting.
> Advanced override setting unification

- setup.cfg
- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/workflow.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/plugins/pdos/__init__.py
- src/aiidalab_qe/plugins/pdos/result.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/workflows/__init__.py
- tests/test_entry_point.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
Follow PR #456 and PR #458 , this PR makes the `pdos` as a plugin. It implements:
- UI part. Only the outline and result panel are added.
- Workchain part.
> make pdos a plugin

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/configuration/pseudos.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/submission/__init__.py
- tests/test_pseudo.py
This PR 
- Move Pseudo selector and setter to `advanced setting`
- add protocol to Pseudo selector and link it with the protocol from the workflow.
> Merge advanced setting

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/workflow.py
- src/aiidalab_qe/app/submission/__init__.py
- tests/conftest.py
The `get_configuration_parameters` method of `ConfigureQeAppWorkChainStep` is hard coded. In principle, it should only need to call the method from sub-settings (plugin's panel). e.g
```
workchain_settings = self.workchain_settings.get_setting_parameters()
advanced_settings = self.advanced_settings.get_setting_parameters()
```
Same for the `setting` method.
In this PR, I make this change for the `WorkChainSettings`. Next PR will be the `AdvancedSettings`.
> use get and set for WorkChain settings

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/workflows/__init__.py
Follow #464 
- add get and set_setting_parameters for `advaced settings`.
- move the logic of getting overrides of `base`, `scf`, `bands` and `scf` to the individual plugin.
- link the `spin_type` and `electronic_type` to the `advanced setting`. Generally, we should only link the `protocol` of the `workchain_settings` to the plugin's setting. However, in the advanced setting, we also need the `spin_type` and `electronice_type`, which we hard-coded. If other plugins also need these values, they should directly access the `self.parent.workchain_settings.spin_type.value`.
> add get and set for advanced settings

- src/aiidalab_qe/app/result/workchain_viewer.py
- src/aiidalab_qe/app/submission/__init__.py
Check the plugin design by installing a plugin from another repository: https://github.com/superstar54/aiidalab-qe-eos. 
One issue is found: the result panel of eos does not show. This PR fixes it.
Now, we have the first `working` version of the plugin design. Cheers!
- add more tests, in the old `plugin_ui` PR, the test coverage is around 80%
- rewrite `set_panel_value` for `advanced_settings`, so we can load data from the process. This needs some improvement from sub-widgets.
- add a clear doc for the plugin.
- add entry_point for step 3, allowing the user to set computer resources for their plugin.
- update the result panel, so that it can combine results from different plugins, e.g. bands and pdos.
> fix result tab

- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/process.py
Related to #455 .
This PR avoids loading nodes in the `WorkChainSelecter`.
On my computer, there are 81 `QeAppWorkChain` processes. 
|   Old   |   This PR   |
|:-------:|:-------:|
|  19 s   |  0.15 s |
|   Old   |   This PR   |
|:-------:|:-------:|
|  22 s   |  7 s |
> Use label in WorkChainSelector

- qe.ipynb
It is recommended to call `load_profile` explicitly. After `aiidalab-widgets-base` if not loaded a warning will throw up.
> load_profile explicitly in qe.ipynb

- src/aiidalab_qe/app/configuration/advanced.py
#477 
We should output the values even if the `override` is not selected. In this case, the default values are used. Since the default values are also with `protocol`, so it safe to use them.
> fix override in get_panel_value for advanced

- src/aiidalab_qe/app/parameters/qeapp.yaml
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/workflows/__init__.py
The codes (`pw_code`, `dos_code`, `projwfc_code`) are hard coded in the builder, which is not good for the plugin design. This PR uses `get_selected_codes`. 
The `get_resources` method is also used to make the code more modularized.
> Remove hard coded codes from workflow

- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/configuration/pseudos.py
- src/aiidalab_qe/app/configuration/workflow.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/summary_viewer.py
- src/aiidalab_qe/app/result/workchain_viewer.py
- src/aiidalab_qe/app/submission/__init__.py
- tests/conftest.py
- tests/test_app_reload.py
- tests/test_configure.py
- tests/test_submit_qe_workchain.py
This PR allows the QeApp to reload GUI parameters when the user selects a process.
- use `aiida.orm.utils.serialize.serialize` to serialize the GUI parameters as yaml, then save it as an extra of the process node. Then load it using the `deserialize_unsafe` method.
- fix set_panel_value for the `advanced_settings`.
- add unit test for reloading the app.
> Reload GUI parameters

- src/aiidalab_qe/common/process.py
> Add button to start new workflow

- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/workflows/__init__.py
- tests/conftest.py
- tests/test_configure.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
> Add clean-up button to control the remote work directory clean

- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/common/process.py
Fixes #161 
adding the kill button to support live-killing of a workchain, just selecting it from the list and clicking on the button.
> Feature/kill button - adding the kill button on top of NodeTree 

- docker/before-notebook.d/71_install-qeapp.sh
- setup.cfg
- src/aiidalab_qe/__main__.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/setup_pseudos.py
- tests/conftest.py
- tests/test_plugins_bands.py
Fix the failed test by set the code dropdown from code uuid.
> Bump awb to 2.1.0a0

- .github/workflows/docker.yml
- docker/Dockerfile
- setup.py
The pre-installation of the app is through run `aiidalab install` from local folder, instead of using `pip install`, this mimics the installation operation from AppStore and prevents issue such as after removing `setup.py` the dependencies are not found.
I'll keep this as draft without adding `setup.py` back and after the new docker stack release with new `aiidalab/aiidalab`, the test should pass.
- The first commit should success because I add the `setup.py` back.
- The second commit is again remove `setup.py`.
> Pre-install app by aiidalab install

- src/aiidalab_qe/app/submission/__init__.py
- tests/test_codes.py
This PR enables the possibility to dynamically show codes in step 3, even if something is changed in step 2 after the confirmation. If you confirm again with a different set of properties, now the shown code is updated, at variance with before.
Moreover, codes that are not shown will not occupy blank space in the app, instead, they are now in the main branch. I achieved this using display instead of visibility.
> Adding dynamic visualization of codes using block layout

- src/aiidalab_qe/plugins/pdos/setting.py
This PR removes the values from the kpoints_distance from the pdos plugin
This PR also fixes the behavior of create_kpoints_from_distance creating a new aiida node
> Removing hardcoded values of NSCF

- src/aiidalab_qe/common/widgets.py
This fix the bug reported previously in #541 , somehow it returned
> Fix AddingTagsEditor Bug

- docs/source/development/architecture.rst
- docs/source/development/plugin.rst
- post_install
- qe.ipynb
- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/configuration/pseudos.py
- src/aiidalab_qe/app/parameters/qeapp.yaml
- src/aiidalab_qe/common/setup_pseudos.py
- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/workflows/__init__.py
- tests/conftest.py
- tests/test_configure.py
- tests/test_pseudo.py
- tests/test_result/test_summary_report.yml
- tests/test_submit_qe_workchain.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
> Bump SSSP to 1.3

- setup.cfg
The pydantic is pinned in https://github.com/aiidalab/aiidalab-qe/pull/416, after the release of `aiida-quantumespresso` it is not needed, this PR bump the aiida-quantumespresso and unpin the pydantic.
> Bump aiida-quantumespresso to 4.4.0 and unpinning pydantic

- .pre-commit-config.yaml
- qe.ipynb
- setup.cfg
- src/aiidalab_qe/app/structure/__init__.py
- src/aiidalab_qe/common/node_view.py
- src/aiidalab_qe/common/setup_pseudos.py
- src/aiidalab_qe/plugins/bands/workchain.py
`aiida-core` from `2.5.0` start to move to using ruff as code formatter, it is much faster.
> Use ruff as code formatter

- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/plugins/pdos/setting.py
- tests/configuration/test_advanced.py
This allows the app to follow the same logic of aiida-quantumespresso plugin, therefore displaying the final kpoint mesh as in the calculation
> removing force_parity from create_kpoints_from_distance

- setup.cfg
- src/aiidalab_qe/common/bandpdoswidget.py
- src/aiidalab_qe/plugins/bands/result.py
- src/aiidalab_qe/plugins/electronic_structure/result.py
- src/aiidalab_qe/plugins/pdos/result.py
- tests/test_plugins_bands.py
- tests/test_plugins_electronic_structure.py
- tests/test_plugins_pdos.py
This PR introduces a new bands_pdos_widget using plotly, the widget include options of drag, pan and toogle , save a snapshot , and download the data.
The formating of the bands/pdos has been moved from the result plugin to the common/bandspdoswidget.py
It allows different selection of atoms to consider, or different representations ( We can modified or create new according to your suggestions)
For spin polarized calculations it represents bands_up in red, and bands_down in blue. For non polarized the line is in black color.
The new `_projections_curated_options` allows to curated SOC pdos. 
The legend has a wheel fixing #552
> New BandsPdosWidget

- src/aiidalab_qe/app/structure/__init__.py
Fixes an oversight from https://github.com/aiidalab/aiidalab-qe/pull/614 where the lithium carbonate example was not added to `Examples` in `__init__.py` and thus couldn't be selected as a structure.
> Examples: Add Lithium Carbonate to List of Examples

- src/aiidalab_qe/plugins/xps/workchain.py
For molecules, we use `gamma_only` and `assume_isolated`. This should be fixed in the aiida-quantumespresso XpsWorkchain, but we don't want to wait for the new PR and release. Thus, we fix it here directly.
I also adjust the `supercell_min_parameter_map,` so it uses the default 8.0 when the user selects the `moderate` protocol.
> fix pw setting for molecule in XPS calculation

- src/aiidalab_qe/app/submission/__init__.py
fix #659 .
Skip setting the code if the code does not exist in the `DEFAULT_PARAMETERS`.
> check code exist in the DEFAULT_PARAMETERS or not

- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/plugins/xas/workchain.py
- src/aiidalab_qe/plugins/xps/workchain.py
- src/aiidalab_qe/workflows/__init__.py
fix #666 
If a plugin has `clean_workdir` default to True, even if the user didn't select the `clean_workdir` box, the plugin still cleans the workdir. This PR assigns the `clean_workdir` to the plugin's builder to make sure the `clean_workdir` is consistent.
> assgin clean_workdir to plugin's builder

- src/aiidalab_qe/app/submission/__init__.py
fix #664 
If code is imported from another user, it is not usable and thus will not be treated as an option in the `ComputationalResourcesWidget`.
> check if the code is installed and usable

- src/aiidalab_qe/app/submission/__init__.py
fix #516 
- The placeholder for the label is generated based on the job.
- The description is default empty.
Here is the screenshot:
> add label and description for the job

- src/aiidalab_qe/app/configuration/workflow.py
- tests/test_configure.py
Only observe to update the `reminder_text` if there is a setting panel.
> Fix reminder_text

- post_install
After installing or updating a plugin package, one needs to restart the daemon with the --reset flag for changes to take effect.
For the moment, aiidalab only restarts the daemon without the—-reset flag, so we need to do it manually.
This is needed for our next release. We can remove this after this https://github.com/aiidalab/aiidalab/pull/424
> restart the daemon with --reset flag manually

- plugin_list.ipynb
fix #696 . Now it shows the correct author list.
> fix plugin.yaml file url

- bumpver_pre_commit.sh
- setup.cfg
This is the last piece in the release workflow.
The newly added `bumpver_pre_commit.sh` script is configured to run automatically by bumpver
before it creates the release commit.
We check for common mistakes, such as making a release commit
in a wrong branch, or trying to push to a wrong remote.
For now, only two checks are implemented:
1. Check that the current branch name matches either `release/*` or `support/*`
2. Check that the remote `origin` is pointing to the origin repository,
and not a fork. Note however that this assumes that `origin` is the default remote
where new branches are pushed. If the user configured a different default remote,
this check will not save them in the current implementation.
- make sure the main branch is up-to-date with origin/main
- make sure the HEAD …
> Add bumpver pre-commit

- src/aiidalab_qe/common/setup_codes.py
It takes 1-2 sec to set up a code, and we have 14 codes (pw, dos, pp, ph, etc.), so around 20 sec in total. Which is not good, and it takes too long to load the container.
I looked into the issue and found that most of the time is used to set up the verdi command, profile and database. Thus it's would be good to combine all code set up as one.
Since the code setup is run in a different thread, thus, using the `InstalledCode` directly will fail when storing the code, as I tested in #695. This PR uses the `python -c` command to run in the `subprocess`. 
The total time to set up all 14 codes is now reduced to 3-5 seconds. Most importantly, setting more codes will not increase the time too much. **This is a temporary solution, but it is better than no solution.** We can use the …
> use python script to setup all codes

- qe.ipynb
- src/aiidalab_qe/common/setup_codes.py
> Fix current year in app

- src/aiidalab_qe/app/configuration/advanced.py
- src/aiidalab_qe/app/structure/__init__.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/widgets.py
- src/aiidalab_qe/workflows/__init__.py
> HubbardStructureData reach by StructureBrowserWidget

- src/aiidalab_qe/app/submission/__init__.py
This PR uses the `get()` method and provides default values to avoid crashing when the `input_parameters` is an empty dict.
> fix parameter retrieval in method `_update_process_label`

- src/aiidalab_qe/plugins/bands/workchain.py
This PR solves an issue that can occurs with working with oblique cell, where due to rounding number it will not include a k-point. 
If you want to reproduce the issue with the current app, use 
[structure-not-stored (25).cif.zip](https://github.com/aiidalab/aiidalab-qe/files/15273135/structure-not-stored.25.cif.zip)
> cleaning 2D path logic

- .github/workflows/ci.yml
- .github/workflows/docker-build-test-upload.yml
- .readthedocs.yaml
- docs/source/blogs/index.rst
Use `uv` installer to speed up installing dependencies for tests + some other CI tweaks brought over from AWB:
- Use FORCE_COLOR to get colored logs in Github UI
- Update actions
- Don't collect code coverage from tests/ folders
> CI: Use uv for installing deps

- .github/workflows/docker-build-test-upload.yml
- docker/Dockerfile
This cuts down the build time by a full minute.
> Use uv to install deps during docker build

- .dockerignore
- .github/workflows/docker-build-test-upload.yml
- Dockerfile
- before-notebook.d/70_prepare-qe-executable.sh
When building the QEApp Docker container, the Quantum Espresso installation into a conda environment is a step that's completely independent from the others. By putting it into a separate Docker build stage, it can be build in parallel (when using buildkit), as:
DOCKER_BUILDKIT=1  docker build .
Also added a `.dockerignore` file. This is important since we're copying the whole directory into the container and we don't want to copy junk inside. Even if we later run `git clean`, once the files are copied, that stay in the fs layers.
Extracted from #781
> Move QE conda install into separate stage

- src/aiidalab_qe/common/bandpdoswidget.py
@AndresOrtegaGuerrero as discussed, I added a slider to control the width of the fat bands. It will only become visible once you enable the fat bands. In agreement with the previous logic, you need to click the update button to adjust the width. The slider covers a range from 10 to 750 meV/atom as the maximum width of a fat band.
> Add slider to adjust fat bands width

- src/aiidalab_qe/common/bandpdoswidget.py
This PR includes text description to the widget 
This PR solves #812
> improving description text in widget

- src/aiidalab_qe/common/bandpdoswidget.py
In #787 , 
I forgot to update the logic for the fat_bands , here is included
Now for only bands calculations and fat bands the labels are propertly display
> update labels for fat_bands

- src/aiidalab_qe/app/wrapper.py
this PR modifies the description of the guide toggle button
> changing guide button label and layout

- src/aiidalab_qe/common/bandpdoswidget.py
This PR allows the widget to be use for vibroscopy plugin to set fermi to zero
> allows fermi_energy to be zero

- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/result/workchain_viewer.py
In PR #844 , the process monitor updates the result tabs in another thread. This leads to an issue: when the user interacts with the result, the widget runs in the thread differently from the one running in the process monitor.
Therefore, triggering the automatic updating of the result tabs is not possible.
In this PR, we don't use process monitor anymore. Instead, we add a button to let the user trigger the update manually. 
I also modified the layout of the buttons (kill, clean) to make the UI pretty.
> Add button to trigger the update of the results tabs.

- src/aiidalab_qe/app/result/summary_viewer.py
This fixes https://github.com/aiidalab/aiidalab-qe/issues/878
> Fixing the structure optimized info in the workflow summary

- src/aiidalab_qe/app/result/utils/download_data.py
This fixes https://github.com/aiidalab/aiidalab-qe/issues/914
> fixing the download of a single QeAppWorkChain

- src/aiidalab_qe/app/result/__init__.py
The logic of the update results button was missed in #921. This PR restores the functionality by adding a `refresh` parameter to the `_update_node_view` method to allow bypassing the node view cache.
Note: a follow-up PR is planned to rethink the way we deal with the `WorkChainViewer` tabs which will render the update results button redundant.
> Restore update results button functionality

- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
- src/aiidalab_qe/common/bands_pdos/model.py
> Chaning pdos control labels

- src/aiidalab_qe/common/widgets.py
> modifications to the EditStructureData Widgets

- src/aiidalab_qe/common/widgets.py
In #933 , by mistake i also modify the logic in the update method causing that the periodicity was not changed. 
This fix this bug
> setting periodicity options to the mapping

- src/aiidalab_qe/plugins/pdos/model.py
- src/aiidalab_qe/plugins/pdos/setting.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
This PR solves the problem with #959 
The solution is to set DeltaE[https://www.quantum-espresso.org/Doc/INPUT_PROJWFC.html#idm30]  (energy grid step eV) from dos.x and projwfc.x. 
Here, we also modified a bit the description of the PDOS plugin tab, plus the addition of the new widget. 
By enforcing the DeltaE to be 0.01 eV we get to see the core level pdos peaks
> adding a widget to control DeltaE in PDOS plugin

- setup.cfg
- src/aiidalab_qe/plugins/pdos/workchain.py
In this PR , we solve the issue of the PDOS and BandStructure not matching the energies. 
Now the PDOS and BANDS match
> upgrade qe-plugin , include nbands_factor to PdosWorkChain

- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/common/panel.py
Based on #946
This PR handles a couple of bugs related to the process node, specifically loading node views and managing the process state.
> Fix process-node-related bugs

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/basic/model.py
- src/aiidalab_qe/app/configuration/basic/workflow.py
- src/aiidalab_qe/app/main.py
This PR moves the spin orbit control from advanced to basic settings. It also simplifies/uniforms the basic settings UI.
Handles #981
> Move spin orbit to basic settings

- src/aiidalab_qe/plugins/pdos/workchain.py
fix #999 
In https://github.com/aiidalab/aiidalab-qe/pull/965, `nbands_factor` is used in `PdosWorkChain`, thus we should not set `nbnd` anymore.
> Do not set `nbnd` for pdos workchain

- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
This PR fixes #899 , 
The max limit of the widget is set to 5.0 eV
> increase fat bands slider max to 5.0 eV

- src/aiidalab_qe/plugins/bands/result/result.py
- src/aiidalab_qe/plugins/electronic_structure/result/result.py
- src/aiidalab_qe/plugins/pdos/result/result.py
This PR addresses the issue in #976
> using a center layout for the widget BandsPdosWidget

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/mixins.py
This PR introduces guards on subsequent steps that inform the user if dependencies have yet to be met, i.e., previous step(s) not confirmed.
- Reduced chances of messing up
- Reduced development complexities (due to reduced error potential)
- Self-guiding app
- *Reduces user exploration
*Not exactly true. The exploration is still available, but now in a prescribed (correct) order.
@cpignedoli @giovannipizzi thoughts?
---
---
> Implement missing-info warnings

- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/model.py
- src/aiidalab_qe/app/parameters/__init__.py
- src/aiidalab_qe/app/parameters/qeapp.yaml
This PR implement a merging mechanism for custom app defaults configurations. Users can now drop a custom `config.yml` in the `/home/jovyan/.aiidalab/quantumespresso/` directory. The file follows the structure of the `qeapp.yml` default configurations file, though it does not strictly require the inclusion of all fields. The custom `config.yml` file is processed and merged recursively into the object created from processing `qeapp.yml`.
Closes #1006
**Note**: I had to modify the updating procedure of relaxation type options and value (PBC-dependent) to accommodate these changes, though I think perhaps this was actually just a bug in that implementation.
> Default workdir clean on demo server

- calculation_history.ipynb
- docs/source/development/plugin.rst
- src/aiidalab_qe/plugins/bands/workchain.py
- src/aiidalab_qe/plugins/pdos/workchain.py
- src/aiidalab_qe/plugins/xas/workchain.py
- src/aiidalab_qe/plugins/xps/workchain.py
- src/aiidalab_qe/utils.py
- src/aiidalab_qe/workflows/__init__.py
fix #1021 
Enable pencil decomposition for all `pw.x` calculations.
**Note**, I still get issue on `projwfc`,
```console
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Error in routine  blk2cyc_zredist (1):
nb less than the number of proc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
> switch on the `-pd` option for pw code

- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/app/wrapper.py
- src/aiidalab_qe/common/widgets.py
This PR introduces a `LinkButton` widget that mimics a `ipywidgets.Button` via an `ipywidgets.HTML` wrapper around an anchor tag (`<a>`).
Resolves #891
Resolves #988
> Fix safari pop-up issue with new `LinkButton` widget

- src/aiidalab_qe/app/result/components/viewer/structure/__init__.py
- src/aiidalab_qe/app/result/components/viewer/structure/model.py
- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
- src/aiidalab_qe/app/result/components/viewer/viewer.py
- src/aiidalab_qe/common/panel.py
- tests/test_plugins_electronic_structure.py
- tests/test_result.py
This PR implements a structure results panel that is always shown. The tab title and source node are dependent on the nature of the calculation as follows:
- No relaxation - title = "Initial structure"; source = `node.inputs.structure`
- Some relaxation - title = "Relaxed structure"; source = `node.outputs.structure`
Auto rendering is adjusted to ensure the initial structure panel is not dependent on having results (there are none) but instead is always auto rendered.
Closes #993
> Implement constant but relaxation-dependent structure results panel

- src/aiidalab_qe/app/configuration/__init__.py
- src/aiidalab_qe/app/configuration/model.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/result/model.py
- src/aiidalab_qe/app/structure/__init__.py
- src/aiidalab_qe/app/structure/model.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/app/submission/model.py
- src/aiidalab_qe/common/mixins.py
- src/aiidalab_qe/common/widgets.py
This PR resolves issues with #1004 (incorrect handling of step-to-step switching/rendering) by treating the app steps more uniformly. It also introduces a simple locking mechanism on submission that disconnects all observations of step confirmation, thus rendering the app in a "locked" state by permanently disabling confirm/submit buttons.
@superstar54 note that this also simplifies the handling of "invalid" dependent steps (referencing your [comment](https://github.com/aiidalab/aiidalab-qe/pull/1004#discussion_r1894083025) on #1004)
> Replace `DependentStep` mixin with proper `QeWizardStep` MVC classes

- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
- src/aiidalab_qe/plugins/bands/result/result.py
- src/aiidalab_qe/plugins/electronic_structure/result/result.py
- src/aiidalab_qe/plugins/pdos/result/result.py
This PR address #1017 , not it just center the plotly widget
> adding a center_layout to get the plot centered

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/basic/model.py
- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/static/templates/workflow_summary.jinja
- src/aiidalab_qe/app/structure/__init__.py
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/common/widgets.py
- src/aiidalab_qe/plugins/bands/model.py
- src/aiidalab_qe/plugins/bands/resources.py
- src/aiidalab_qe/plugins/pdos/__init__.py
- src/aiidalab_qe/plugins/xas/setting.py
- tests/test_result.py
This PR enforces sentence casing throughout the app.
Closes #987
> Sentence-case

- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/app/static/styles/variables.css
- src/aiidalab_qe/common/widgets.py
- tests_integration/test_app.py
This PR uses the experimental `:has` CSS selector to apply background colors to the accordion item headers bases on the state of the accordion item's content (the wizard steps). If `:has` is not supported by the browser (old version), the colors simply do not apply. 
Closes #989
---
> Implement state-dependent accordion background colors

- src/aiidalab_qe/app/result/components/summary/model.py
Only escaped if exit status was 0, but need to escape if it is `None`
> Check for null exit status

- setup.cfg
Recent pymatgen release (2024.8.9) marks `is_rare_earth_metal` as deprecated on 1.1.25, from which point it has raised a test-failing deprecation warning. This PR aims to resolve this matter by fixing the dependency to the 2024.5.1. Note that we don't use `is_rare_earth_metal` in the app or plugin. The warning is raised because pymatgen was still using it in certain places. Assumption is that they will remediate this shortly, at which point, we can soften the hard dependency (if required).
> Fix pymatgen dependency

- src/aiidalab_qe/app/result/components/summary/model.py
- src/aiidalab_qe/app/result/components/summary/schema.json
- tests/test_result.py
This PR uses pymatgen symmetry analyzer classes to extract symmetry group information from the structure for use in the summary.
Resolves #1053
> Handle space/point-group correctly

- setup.cfg
- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
- src/aiidalab_qe/common/widgets.py
Here i am addressing #1050 
I am using @superstar54 (He will be co-author of the PR as well) code of TableWidget, with some modifications
https://github.com/user-attachments/assets/d74bc4fc-42b0-4168-934a-045ebf7ad30c
> Add atom table and set cell tab as default

- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
- src/aiidalab_qe/common/widgets.py
Added functionality to the structure widget to synchronize the atom table with the selection in the widget.
The widget now supports bidirectional selection behavior: selecting rows in the table updates the widget's selection, and selecting items in the widget updates the table's selection.
https://github.com/user-attachments/assets/6112d22b-e890-4260-ae55-3e65c587e69a
> Adding effect of selecting the table from the structure widget

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/workflows/__init__.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
This pull request addresses issue #748 by introducing a widget that allows users to set the maximum number of steps for structural relaxation calculations in Quantum ESPRESSO. The default is 50 steps, but some systems may require more to achieve convergence. This feature prevents premature termination of calculations due to insufficient iteration limits. Additionally, systems requiring tighter convergence criteria, such as those involved in phonon calculations, may benefit from increased step limits.
> Adding relax max_step widget

- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
This PR closes https://github.com/aiidalab/aiidalab-qe/issues/928
The displayed information includes the PK, label, description, creation time, and number of atoms.
Structure Creation Details: Knowing when the structure was created and its PK helps users efficiently search for and reuse it in new calculations. The PK also helps to locate the structure within the database.
Interaction with Selection Widget: The number of atoms reminds the user the structure's size (on the tab), enabling them to interact effectively with the selection widget.
> Add info relaxed structure results tab 

- src/aiidalab_qe/common/widgets.py
This PR addresses the issue of inconsistent row selection states in the table , in particular when the widget clear a selection in the table , but if you click the table it might retain extra information of the selection. 
An updateSelection function is included to synchronize the selectedIndices array in JavaScript with the selected_rows list from Python
Old
https://github.com/user-attachments/assets/8106b48f-f547-4e41-babc-989715613860
New 
https://github.com/user-attachments/assets/7028ae97-47ea-4903-9158-d4bac43dfd97
> Synchronize TableWidget row selection

- src/aiidalab_qe/plugins/xas/resources.py
- src/aiidalab_qe/plugins/xps/__init__.py
- src/aiidalab_qe/plugins/xps/resources.py
Fix #1070 
In the new code resource design, every property plugin needs a resource panel, even if the plugin does not have an additional code other than the `pw.x`, as in the XPS plugin.
> Add XPS resource

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/configuration/basic/basic.py
- src/aiidalab_qe/app/configuration/basic/model.py
- src/aiidalab_qe/app/configuration/model.py
- src/aiidalab_qe/common/mixins.py
- src/aiidalab_qe/utils.py
This PR uses the QE plugin `get_starting_magenetization` utility function to set default initial magnetic moments for the structure when magnetism is turned on. The defaults are set to the default magmom provided by the utility scaled by the Z valence value for the element defined in the selected pseudopotential. Note that for those elements of a zero magmom default, a general default magnetization of 0.1 is returned.
If multiple tags are provided for the same species, a warning is displayed providing some instructions for antiferromagnetic configurations.
Closes #982
---
> Use plugin utility to set default starting magnetization

- src/aiidalab_qe/app/result/__init__.py
- tests/test_result.py
This PR does the following:
1. Reorder results tabs as Summary | Status | Results
2. Sets the default tab dynamically (Status if running, Results if complete)
> Shuffle results panel top-level tabs and update default selection

- src/aiidalab_qe/app/result/components/viewer/structure/model.py
- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
- src/aiidalab_qe/app/static/styles/results.css
- src/aiidalab_qe/app/static/styles/structure.css
- src/aiidalab_qe/common/panel.py
- tests/test_result.py
This PR implements a toggleable structure view allowing users to toggle between the initial and relaxed structures in a single panel. Toggle controls are sensitive to the relaxation state (not relaxed, relaxing, relaxed):
- Not relaxed: no toggle button
- Relaxing: toggle button disabled until done, with responsive tooltip
- Relaxed: active toggle button
Clicking the toggle button will update the title, toggle description, and structure view, info, and coordinates table.
> Implement structure view toggle

- src/aiidalab_qe/common/bands_pdos/model.py
> Group bands by angular momentum by default

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/hubbard/hubbard.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/pseudos.py
- src/aiidalab_qe/app/configuration/advanced/smearing/smearing.py
- src/aiidalab_qe/common/widgets.py
- tests/configuration/test_advanced.py
- tests/test_pseudo.py
This PR is mostly cosmetic, applying the following styles to the advanced settings panel:
- Vertically align widgets
- Add more sub-section headings and emphasize style (`h2` & `h4` tags)
- Make widget labels clear and concise
- Add more help text (thanks @AndresOrtegaGuerrero 🙏)
- Reduce help text overflow where appropriate
- Move units from label to right of input widgets (using new `HBoxWithUnits` widget)
- Move Hubbard U check box down
- Covert functional selector to toggle buttons
- Reduce verbosity in pseudopotential widgets by moving some description up into help text
- Add link for more info on pseudopotential cutoffs (thanks @AndresOrtegaGuerrero 🙏)
---
> Spruce up advanced panel styling

- src/aiidalab_qe/common/panel.py
This PR simply translates "WAITING" states to "RUNNING", since workflows "always" WAIT on RUNNING calculations. This makes it more clear to the user that things are running. Workflows awaiting other calculations are in a "QUEUED" state.
> Translate `waiting` workflow state to `running`

- .readthedocs.yaml
This PR addresses a recent ReadTheDocs deprecation. See [blog](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for details.
> Explicitly state Sphinx configuration path

- plugin_list.ipynb
The plugin management page uses the same width as other pages.
> Set full width for plugin management page

- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/app/submission/global_settings/model.py
- src/aiidalab_qe/app/submission/global_settings/setting.py
- src/aiidalab_qe/app/wrapper.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/common/widgets.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
This PR provides a top level button and a link in step 3 to the new external resource setup notebook in aiidalab-home (https://github.com/aiidalab/aiidalab-home/pull/188). It also removes the code setup widget buttons from the individual code selectors in step 3 (in favor of the external notebook).
> Utilize external resource setup notebook for code management

- src/aiidalab_qe/common/panel.py
- tests/test_result.py
Thie PR fixes incorrect logic in deciding which widgets to add to a results panel that was incorrectly rendering status notification for completed workflows.
> Fix rendering logic of results panel controls

- src/aiidalab_qe/app/result/components/status/status.py
- src/aiidalab_qe/app/result/components/status/tree.py
- src/aiidalab_qe/app/static/styles/status.css
- src/aiidalab_qe/common/widgets.py
This PR handles a styling issue (casuing some buttons to have odd height) and a process label issue (now handling "vc-" labels). It also adds a link to the docs to learn more about how the restart feature works.
> Fix process tree issues

- before-notebook.d/43_start-hq.sh
This old script assumes a cgroupv2 environment, but the issue arises because some system doesn't have the required cgroupv2 files (/sys/fs/cgroup/cpu.max and /sys/fs/cgroup/memory.max). 
- If cpu.max and memory.max are missing, fall back to cgroupv1
- If neither cpu.max nor cpu.cfs_quota_us exists, use default values.
> Handle cpu and memory check gracefully

- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
- src/aiidalab_qe/common/bands_pdos/model.py
As requested by Carlo, this PR we add widget to change the width of the plots of the bandspdosplot widget. 
For instance , in a 1D GNR the original 
can be modified to 
The same applied for the bands+pdos plot
The user can do modifcations to obtain
> Adding widget to control aspect ratio of plot 

- Dockerfile
I think since the folder is used for the aiida-pseudo installation workaround, this change is needed. I don't know on the github CI it does not require this change, I need this to run `docker build -it ` in my local laptop.
> UV_CACHE_DIR need do be the ARG for stage3 build

- src/aiidalab_qe/app/configuration/__init__.py
#984 neglected to address this. The hack ensures that when a process is loaded, the unpacked parameters applied to `spin_orbit` in the advanced model are synchronized with the basic model (and UI by observation).
> Synchronize `spin_orbit` on process load

- Dockerfile
- before-notebook.d/00_untar-home.sh
This enables running the image on Renku.
See the `qe-test-tasko` session launcher on https://renkulab.io/v2/projects/jusong.yeu/aiidalab-qe-app.
The session launcher has the following specs:
> fix: enable running image on Renku

- src/aiidalab_qe/app/result/components/summary/download_data.py
- src/aiidalab_qe/common/widgets.py
Change message to clarify that the waiting time is due to AiiDA creating the file, not the user's network.
Closes #1109
> Clarify raw data / archive download message

- src/aiidalab_qe/app/wizard_app.py
- src/aiidalab_qe/common/widgets.py
Fixing an annoying CSS issue where a scroll bar keeps (dis)appearing due to the way the `fa-spin` class is implemented.
> Fix loader margins

- src/aiidalab_qe/common/panel.py
Moved observation of code selector above its initial setting to ensure that the resource update, which also sets max CPUs, is triggered.
> Correct observation order of code selection

- src/aiidalab_qe/plugins/pdos/workchain.py
This fixes https://github.com/aiidalab/aiidalab-qe/issues/1122
This because we risk to have too many processors and few plane waves. The problem is also present for projwfc.x, but there is not -pd option.
For projwfc.x, we can simply add something in the documentation of the app.
> Adding pencil decomposition for dos.x by default

- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/result/components/viewer/structure/structure.py
- src/aiidalab_qe/app/structure/__init__.py
I am testing the app inside normal notebooks, and this PR fixes:
- nglview not show in step 1 and step 4
- cutoffs are wrong in pseudo
> Fix nglview not show

- calculation_history.ipynb
- delete.ipynb
- download.ipynb
- examples.ipynb
- plugin_list.ipynb
#1128 incorrectly applied `%%capture` to the style-loading cells, effectively consuming the stylesheets. This PR removes the captures.
> Discard capturing of loaded stylesheets

- src/aiidalab_qe/common/widgets.py
Fixes an issue with button styles
> Apply button color class to `LinkButton` widget, not its internal anchor tag

- setup.cfg
The new QE plugin introduces the use of "tetrahedra_opt" in the NSCF calculation of the PDOS Workflow. 
This will close #959 , and It will allow the correct calculation of pdos for molecules as well.
> Bump QE plugin to 4.9

- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/wizard_app.py
- src/aiidalab_qe/common/__init__.py
This PR adds a flag, which if True, adds an `Output` widget at the bottom of the app, accompanied by a reset button. The widget can then be passed down to any part of the app that needs to be tested.
The PR hardcodes one use-case - monitoring. The `ProcessMonitor` was recently changed (https://github.com/aiidalab/aiidalab-widgets-base/pull/669) to accept an output widget and use it to log exceptions in monitored callbacks. This PR passes the output widget (if included) down to the `ProcessMonitor` instance, exposing its exceptions. This is useful for debugging issues in the results step.
> Implement logging widget (mostly for devs)

- setup.cfg
Depend on the stable version of the awb library.
> Bump aiidalab-widgets-base dependency

- setup.cfg
The latest plotly version (v6.0) needs Jupyter Notebook 7.0.
This PR pins the version 5.24, which I tested and work in our docker environment.
> Pin plotly version

- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/basic/basic.py
- src/aiidalab_qe/app/static/styles/custom.css
This PR adds a note in the magnetization section and one next to the electronic type selector informing users about the limitations in combining the insulator and magnetism options. It also styles info messages in the basic settings as inline info alerts to grab the users attention.
> Add information about magnetism feature limitations for insulators

- src/aiidalab_qe/app/result/components/status/status.py
This PR reverts to using the AWB node view widget, which now supports caching (https://github.com/aiidalab/aiidalab-widgets-base/pull/686).
> Use AWB's `AiidaNodeViewWidget` to handle node views

- src/aiidalab_qe/app/result/components/summary/model.py
- src/aiidalab_qe/app/submission/model.py
- src/aiidalab_qe/workflows/__init__.py
- tests/conftest.py
Currently, the `relax` port always exists in the builder even if the `relax` is not required, and the summary report also depends on the `relax` input.
This PR fixes this by:
- If no relaxation is required, the `relax` port will be popped out.
- The summary parameters are read from `ui_parameters` instead of `relax` port.
This fixes the wrong number of jobs in the status tree.
> Pop relax port if not relaxation

- setup.cfg
XPS/XAS plugins are migrated out, so the `aiida-qe-xspec` should not be a dependency.
> Remove aiida-qe-xspec

- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/common/widgets.py
Styles were applied to the `LinkButton`'s inner anchor tag. Here, a `link-button` CSS class is added directly to the `LinkButton` class (inherits `ipywidgets.HTML`).
> Fix `LinkButton` styles

- src/aiidalab_qe/common/process/tree.py
As the current implementation makes significant use of AiiDA nodes, good to cache them. Here I use a cache dict to store the node instance per thread id, to avoid DB session issues.
> Cache node per thread to reduce DB calls

- src/aiidalab_qe/app/result/__init__.py
This PR makes the workflow status message more clear w.r.t failures. It provides a template "Workflow status: <status>", with status defined as "Excepted", "Killed", or "Failed", depending on the process state.
Closes #1169
> Make workflow status more clear/accurate

- tests/test_status.py
The test is time-dependent due to race conditions. This PR adds a small delay to ensure the main thread spends enough time adding branches to ensure that the monitoring thread will also attempt it.
> Add a delay when testing tree monitor updates

- Dockerfile
- before-notebook.d/42_setup-hq-computer.sh
- before-notebook.d/43_start-hq.sh
I closed PR #1191 and created a new one with the same content, but this time from the main repository instead of a forked one.
As discussed with @unkcpz  and @edan-bainglass , we propose the following changes:
- Use `localhost` as the default computer's name in the Docker image, which is consistent with the app's default setting. This also makes it easy for plugin developers to set up their code.
- Keep the old computer from the full-stack image but change its label to `localhost-non-hq`, as @edan-bainglass suggested. The reason to keep it, because @unkcpz  suggested, if we delete the old `localhost`, we may delete the user's data in the volume that is associated with the `localhost`.
> Label the computer as `localhost` in the Docker image

- setup.cfg
Plotly requires the Kaleido package to export images in SVG and PDF formats. This dependency affects the electronic structure plugin, causing a bug when users attempt to download SVG files.
> Include Kaleido package

- Dockerfile
Fix #1211 
There is a permission error for the .conda folder when running with aiidalab-launch.
It is usually safe (and preferable) to let .conda be recreated on the fly each time, because .conda typically just holds local environment information, caches, or references to available environments.
> [Fix] Permission error for .conda folder in the Docker image

- docs/source/conf.py
- setup.cfg
- src/aiidalab_qe/version.py
Release the alpha version of `v25.04.0` to include some critical fixes since `v25.03.0`.
> Bump version v25.03.0 -> v25.04.0a1

- Dockerfile
- setup.cfg
- tests_integration/test_image.py
This PR tries to pre-set up some necessary codes/pseudos for some core plugins that we maintain.
- **Bader**: install Bader in the same conda env as the QE
- **Wannier90**: because we need to use the latest source code from GitHub, we compile Wannier90 from scratch. 
- **AiiDA codes**: Bader, Wannier90, PythonJob
- **Pseudos**: Bader needs PAW, and Wannier90 needs SSSP 1.1.
With all this added, the size compared to the previous one:
| Image       | Size   |
|-------------|--------|
| New image   | 5.5 GB |
| Old image   | 4.92 GB |
> Add bader, wannier90 and pythonjob codes

- src/aiidalab_qe/app/structure/__init__.py
If one opens step 1 then quickly closes it, the NGLView widget is rendered while its parent is closed, leading to a computed width of 0 for the NGLView widget. This is a persistent issue not only with the NGLView, but also other similar viewers (e.g. WEAS).
This PR ensures that opening step 1 refreshes the NGLView **every time**!
> Always refresh NGLView to ensure it is indeed rendered

- Dockerfile
In my previous PR, I didn't aware that git is need by the app to install plugins, and cleaned the git to reduce the size of the image. This PR add it back.
> Do not remove git

- src/aiidalab_qe/app/main.py
- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/app/static/styles/infobox.css
- src/aiidalab_qe/app/static/styles/variables.css
- src/aiidalab_qe/app/static/templates/about.jinja
- src/aiidalab_qe/app/static/templates/guide.jinja
- src/aiidalab_qe/app/submission/__init__.py
- src/aiidalab_qe/app/wrapper.py
- src/aiidalab_qe/common/widgets.py
- tests/test_wrapper.py
This PR does the following:
- Moves Getting started content over to About
- Renames Getting started as Tutorials
- Groups toggle buttons and external links separately
- Uses CSS to dynamically control button layout
---
https://github.com/user-attachments/assets/ebb45a76-011d-4c36-aed6-778938bcbf34
> Reorder top controls

- src/aiidalab_qe/common/process/tree.py
- src/aiidalab_qe/plugins/bands/__init__.py
- src/aiidalab_qe/plugins/pdos/__init__.py
- tests/test_status.py
This PR introduces a new key to a plugin's outline:
```
{
...
"metadata": {
"process_labels": {
"MyWorkChain": "Super cool workflow",
"MyCalcJob": "Super important calculation",
...
}
}
}
```
By suggestion (@superstar54), we nest the `process_labels` key under `metadata` for future extension.
In the process tree, we concatenate these labels from discovered plugins to the process-class-name-to-human-readable-label map.
> Use new `metadata.process_labels` entry point to fetch plugin process human-readable labels

- src/aiidalab_qe/common/bands_pdos/bandpdosplotly.py
- tests/test_plugins_bands.py
- tests/test_plugins_electronic_structure.py
- tests/test_plugins_pdos.py
As discussed in the meeting, there was a bug when plotting only the (P)DOS.
The x-axis was labeled as "Density of States" instead of "Energy (eV)" and no y-label was added.
> Fix labels in `BandsPdosPlotly`

- src/aiidalab_qe/common/widgets.py
Discussed with @mikibonacci and @giovannipizzi 
It is possible to generate slices in the edit atom tags panel, e.g., `1..5` to select the sites with indices `[1, 2, 3, 4, 5]`. However, in case of a structure with 5 sites, `1..10` would fail and the table wouldn't even appear. In our discussion we agreed that we would expect a behavior similar to lists in Python, i.e., we would expect all indices to be selected/printed, as the maximum of the slice is larger than the number of sites.
> Fix selection of indices in `Edit atom tags`

- Dockerfile
Fix #1265 
Hi @mikibonacci , installing the vibroscopy using `uv` failed, but using `pip` directly works. I tested the image and ran a phonon calculation, it works fine.
So I think we use this temporary quick fix, and look into the issue in the future when we get time.
> Fix installation of vibroscopy plugin in the image

- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- tests/configuration/test_advanced.py
Pinging @edan-bainglass who was refactoring this, but also @mikibonacci and @AndresOrtegaGuerrero as discussed.
This PR will address #1248.
The previous logic was a bit convoluted and resulted in the problem that it doesn't work with tags, see the issue for an example. 
Before describing in more detail, I believe that the fix can be very simple. We simply remove any tags by using `kind.name` and then access the default magnetic moments from the AiiDA-QE plugin.
------------------
Why the current version doesn't work.
Taking `Ni2` with kinds `Ni1` and `Ni2` as an example. First, we call https://github.com/aiidalab/aiidalab-qe/blob/9a7cc724c18413cecb81f8bdc4dfb29638e068bb/src/aiidalab_qe/app/configuration/advanced/magnetization/model.py#L96-L107
which sets `self. …
> Fix default magnetic moments for atoms with tags

- .github/workflows/docker-build-test.yml
- .github/workflows/docker-build-upload.yml
Fix https://github.com/aiidalab/aiidalab-qe/issues/1271
Previously, there was only one action to:
- build the image and upload (amd64 ~8mins, arm64 ~2h)
- test the app using the built image
Therefore, one needs to wait 2 h to see the result of the test.
In this PR, we separate the action into two:
- build-test: build only the amd64 (only ~ 8mins), and test the app
- build both amd64 and arm64 and upload ( ~ 2h)
For a normal PR from the fork, the `build-upload` will not triggered.
> Split the action into: build-upload and build-test

- Dockerfile
`aiidalab-qe` will install `pyhonopy==2.38`, and the `aiidalab-qe-vibroscopy` needs `phonopy==2.25.0`.
A quick solution: when building the image, we first uninstall the one installed by `aiidalab-qe` in the system's conda, and then install the `aiidalab-qe-vibroscopy`.
> Fix the phonopy version in the image

- .github/workflows/docker-build-upload.yml
The new release `v25.04.0` build and push the docker image [v25.04.0](https://hub.docker.com/layers/aiidalab/qe/v25.04.0/images/sha256-c00ddb83ba26ce32153fdc9ba231b647e132c6386bcf595d39083ac5686bd8bc)
But there is still one issue: it does not create a `latest` tag, in this PR, we add the `latest` tag if the branch start with `v` and does not contain `a`. (for this PR, I use `alpha` because I will make an alpha release later to check if this works. We need to change `alpha` to `a back if it works)
> Add `latest` tag

- .github/workflows/docker-build-upload.yml
This condition ensures that the manifest creation only occurs for tags that start with `refs/tags/v` and do not include `a`, `b`, or `rc`.
> Update the condition to build latest

- .github/workflows/docker-build-upload.yml
Use `github.ref_name` instead of `github.ref` to avoid matching unwanted characters from the static 'refs/tags/' prefix when filtering out pre-releases (a, b, rc).
> prevent false negatives in tag filter by using ref_name

- plugins.yaml
`aiida-qe-xspec` introduces `post-install` script to download and import the core-hole pseudopotentials.
> Add post-install script for the `aiida-qe-xspec` plugin

- Dockerfile
I noticed a clear issue where the image size is bloated by installing the compilation and lapack toolchains. These need to be installed in the same step as they are removed, otherwise they stay in the Docker layer.
Also I would strongly recommend to put all this compilation logic into a script and call it from Dockerfile, as the Dockerfile has become very messy.
> Decrease QeApp images size

- examples.ipynb
- src/aiidalab_qe/app/utils/examples_importer.py
- src/aiidalab_qe/app/wrapper.py
- src/aiidalab_qe/common/widgets.py
- src/aiidalab_qe/plugins/electronic_structure/__init__.py
This PR refactors and restructures the examples importing feature to fit with the overall plugin architecture.
Plugin developers can now provide examples in their own examples repo (recommended) by registering in their end point the examples repo as follows:
```
"examples": {
"repo": <plugin-examples-repo-without-github-prefix>,  -> e.g., aiidalab/aiidalab-qe-examples
"tag": 1.0,  -> follows rules to be provided in docs
"path": <archives-path>,  -> optional, defaults to `root/archives`
"metadata_path": <examples-metadata-file-path>  -> optional, defaults to `root/examples.json`
}
```
A tab will be added in the importer widget for the providing plugin. The plugin examples list is fetched and populates the selector.
- Plugin list fetching should trigger on tab switch (lazy fetch)
- …
> Restructure examples importing feature in line with plugin architecture

- src/aiidalab_qe/app/configuration/advanced/advanced.py
Here we reduce the number of decimals points to be displayed ,
This way, we avoid displaying numbers like 1.9999999999999 without exponential notation.
For example , 
I also lowered the minimum allowed SCF threshold to 1e-18. For systems with more than 120 atoms, we sometimes need thresholds around 1e-14 for vibrational calculations, so this small adjustment makes that possible.
> Reduce the number of decimal points to displayed

- src/aiidalab_qe/plugins/pdos/model.py
- src/aiidalab_qe/plugins/pdos/setting.py
This allows the PDOS plugin to use the custom NSCF k-point distance for display.
> Display custom NSCF kpoint distance 

- src/aiidalab_qe/app/result/components/viewer/structure/model.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/plugins/electronic_structure/result/model.py
- src/aiidalab_qe/plugins/electronic_structure/result/result.py
- tests/test_plugins_bands.py
- tests/test_plugins_electronic_structure.py
- tests/test_plugins_pdos.py
Implement the feature to save and load the result panel state.
- Add save and load state button for the result panel
- The state parameters are saved as "result" in the `node.base.extras`.
Take the electronic structure as an example (only a draft)
> Save and load result panel state

- src/aiidalab_qe/app/result/components/summary/model.py
- src/aiidalab_qe/app/result/components/summary/schema.json
- tests/test_result/test_summary_report.yml
Adding pseudopotentials to summary (filename + pk per kind)
> Show pseudopotentials in summary

- setup.cfg
- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/pseudos.py
- src/aiidalab_qe/app/result/components/summary/model.py
- src/aiidalab_qe/app/result/components/summary/schema.json
- src/aiidalab_qe/app/static/styles/custom.css
- src/aiidalab_qe/app/static/templates/workflow_summary.jinja
- tests/configuration/test_advanced.py
- tests/conftest.py
- tests/test_pseudo.py
- tests/test_result/test_summary_report.yml
Motivated by #1299
This PR aims to make the pseudopotential uploaders compatible with the various changes that came after its initial implementation.
- **Rejected uploads** (accompanied by a dedicated notification for each)
- Cases 
- Invalid UPF
- Wrong element
- Valid upload that shares a filename with an existing one (in the DB)
- Behavior
- No change to the UI/model
- **Accepted uploads** (again, with clear notifications)
- Cases
- Identical md5 (replaces upload with existing entry from DB)
- Valid upload
- Behavior
- Set functional/library/family to `None`
- Show permanent warning regarding the custom state, the need for functional consistency, and how to reset to defaults
- In all cases, cutoffs remain consistent (i.e., max across all pseudos, regardless if custom or default)
- For …
> Fix PP upload widget

- setup.cfg
- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- tests/test_submit_qe_workchain/test_create_builder_default.yml
Some inhomogeneous systems may fail to converge with the default Broyden mixing scheme. In such cases, adjusting the mixing_beta parameter or selecting an alternative mixing mode can be essential. Expert users who tune these settings appropriately can often achieve significantly faster and more reliable convergence.
Closes #1357 
Where the user was not able to converge its system.
The PR includes two controls in the advanced settings for the mixing beta and the mixing mode: 
Mixing beta is by default 0.4 in aiida-quantumespresso , and if failure it starts reducing it 
Mixing mode is plain by default as well as in aiida-quantumespresso
> Feature Mixing mode controls

- src/aiidalab_qe/app/configuration/advanced/subsettings.py
- src/aiidalab_qe/app/result/__init__.py
- src/aiidalab_qe/app/result/components/__init__.py
- src/aiidalab_qe/app/utils/calculation_history.py
- src/aiidalab_qe/app/wizard_app.py
- src/aiidalab_qe/common/bands_pdos/bandpdoswidget.py
- src/aiidalab_qe/common/process/tree.py
- src/aiidalab_qe/common/widgets.py
- src/aiidalab_qe/plugins/electronic_structure/result/result.py
Based on #1362 
The `LoadingWidget` moved to AWB in https://github.com/aiidalab/aiidalab-widgets-base/pull/685. This PR discards the widget in this repo and points all imports to AWB.
> Discard local `LoadingWidget` in favor of AWB

- src/aiidalab_qe/app/configuration/advanced/advanced.py
- src/aiidalab_qe/app/configuration/advanced/convergence/convergence.py
- src/aiidalab_qe/app/configuration/advanced/convergence/model.py
- src/aiidalab_qe/app/configuration/advanced/general/__init__.py
- src/aiidalab_qe/app/configuration/advanced/general/general.py
- src/aiidalab_qe/app/configuration/advanced/general/model.py
- src/aiidalab_qe/app/configuration/advanced/hubbard/hubbard.py
- src/aiidalab_qe/app/configuration/advanced/hubbard/model.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/magnetization.py
- src/aiidalab_qe/app/configuration/advanced/magnetization/model.py
- src/aiidalab_qe/app/configuration/advanced/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/pseudos.py
- src/aiidalab_qe/app/configuration/advanced/smearing/model.py
- src/aiidalab_qe/app/configuration/advanced/smearing/smearing.py
- src/aiidalab_qe/app/configuration/advanced/subsettings.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/plugins/pdos/model.py
- tests/configuration/test_advanced.py
- tests/conftest.py
- tests/test_configure.py
Based on #1361
Recent work updating/extending the advanced settings (e.g., #1355, #1358) has motivated switching from a vertical scroll to a horizontal one (i.e. tabs).
> Split advanced settings into tabs

- src/aiidalab_qe/app/configuration/advanced/pseudos/model.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/pseudos.py
- src/aiidalab_qe/app/configuration/advanced/pseudos/uploader/uploader.py
- tests/test_pseudo.py
Per team discussion, this PR does the following:
- ~~Add checkbox to include FR families when in non-SOC state~~
~~Unfortunately, `ipywidgets.ToggleButtons` is designed to auto-select the first option on change of options. Hence, updating the family options on checkbox state change results in a reset of the current selected family to the first available option. There is no apparent public API (or hacking path) for blocking this. One can save the previous library and reset it after, but the UX is not great, as the user sees the bounce between current to first and back to current (if available). Not great, but doable if team requests it. Pinging @giovannipizzi.~~
The checkbox has been removed in favor of always showing the FR families. The text has been adjusted. @AndresOrtegaGuerrero if …
> Update pseudopotentials panel

- src/aiidalab_qe/common/mixins.py
- src/aiidalab_qe/common/mvc.py
- src/aiidalab_qe/common/panel.py
- src/aiidalab_qe/utils.py
This PR manually reverts #1375.
#1375 introduced a hack to recover static analysis for ipywidgets/traitlets classes. Further research suggests that this was an issue due to a "recent" release of the `pyright` package (used by `pylance`). This is addressed by https://github.com/ipython/traitlets/pull/918. For the time being, downgrading `pylance` to `2024.12.1` restores static typing. Once `traitlets` releases a new version, we should consider upgrading, for the fix, but also to stay up-to-date if possible. If and when we upgrade, `pylance` may be updated as well.
> Discard `traitlets` typing hack

- src/aiidalab_qe/common/widgets.py
The MVC redesign introduced code models corresponding to individual code resources selector widgets. The code models handle code fetching. However, the automatic code fetching done in the AWB widget was not yet disabled due to failures in testing. This has sense been fixed. This PR disables AWB's auto code fetching, leaving the work for the code models.
> Don't fetch codes in AWB
